version: '3.9'

services:
  large-data-laravel:
    build:
      context: .
      dockerfile: ./.docker/laravel/Dockerfile
    image: large-data-laravel
    container_name: large-data-laravel
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - large-data-network
    env_file:
      - ./laravel/.env.local
    tty: true
    working_dir: /app
    volumes:
      - ./laravel:/app
    command: bash -c "composer install --optimize-autoloader && php artisan migrate && php artisan serve --host=0.0.0.0 --port=80"
    depends_on:
      - large-data-db

  large-data-db:
    container_name: large-data-db
    image: mariadb:11.1.3
    restart: unless-stopped
    ports:
      - 3306:3306
    networks:
      - large-data-network
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=large-data-db
    volumes:
      - large-data-db:/var/lib/mysql

  large-data-phpmyadmin:
    container_name: large-data-phpmyadmin
    image: phpmyadmin:5.2.0
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      - large-data-network
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: large-data-db
      PMA_PORT: 3306      
      PMA_USER: root
      PMA_PASSWORD: root
      MEMORY_LIMIT: 1024M
      UPLOAD_LIMIT: 1024M
    depends_on:
      - large-data-db

networks:
  large-data-network:
    name: large-data-network
    driver: bridge

volumes:
  large-data-db:
    name: large-data-db
